import type { Metadata } from "next";
import { Hero } from "@/components/blocks/hero";
import { FrameworkCard } from "@/components/blocks/framework-card";
import { CTABlock } from "@/components/blocks/cta-block";
import { FRAMEWORKS } from "@/lib/frameworks";

export const metadata: Metadata = {
  title: "Frameworks",
  description:
    "Annual Tabletop is mapped to NIST CSF 2.0, NIST 800-84, FEMA HSEEP, CISA CTEPs, CJIS v6.0, HIPAA §164.308, FFIEC, PCI 12.10, and CMMC IR.L2-3.6.3.",
};

/** IA 3.4: Frameworks. */
export default function FrameworksPage() {
  return (
    <>
      <Hero
        eyebrow="Frameworks"
        title="Built for the frameworks our buyers are graded on."
        subtitle="Nine frameworks at launch. Crosswalks are generated by Atlas and embedded in every AAR — no one glues them in after the fact."
        primaryCta={{ label: "Try the demo", href: "/demo" }}
        textOnly
      />

      <section className="py-16">
        <div className="container-wide">
          <ul className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            {FRAMEWORKS.map((framework) => (
              <li key={framework.slug}>
                <FrameworkCard framework={framework} />
              </li>
            ))}
          </ul>
        </div>
      </section>

      <section className="bg-paper-50 py-16">
        <div className="container-tight">
          <p className="eyebrow mb-3">How we keep crosswalks current</p>
          <h2 className="font-serif text-3xl font-semibold tracking-tight text-navy">
            The crosswalks update the day the framework updates.
          </h2>
          <p className="mt-4 max-w-prose text-ink-700">
            When NIST 800-61 moves to r3, or CJIS to v6.1, or CSF adds a new
            subcategory, Atlas is re-pointed at the new source document and the
            crosswalks are regenerated. Your AAR template stays aligned with
            the version your auditor is about to reference.
          </p>
        </div>
      </section>

      <CTABlock title="Try a framework-aligned exercise in 90 seconds." />
    </>
  );
}
