import Link from "next/link";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

/**
 * IA 3.1 block 7 + Section 8: visible 1-page AAR snippet on parchment.
 * The AAR is the single most concrete proof of the product.
 */
export function AARSnippet({ className }: { className?: string }) {
  return (
    <section
      aria-labelledby="aar-sample"
      className={cn("py-20", className)}
    >
      <div className="container-wide grid gap-10 lg:grid-cols-[1fr_1.1fr] lg:items-center">
        <div>
          <p className="eyebrow mb-3">Audit-ready AAR</p>
          <h2
            id="aar-sample"
            className="font-serif text-3xl font-semibold tracking-tight text-navy sm:text-4xl"
          >
            The artifact your auditor actually wants.
          </h2>
          <p className="mt-4 max-w-prose text-base leading-relaxed text-ink-700">
            Every Annual Tabletop session ends with an HSEEP-conformant
            After-Action Report. Decisions captured. Framework crosswalks built
            in. Recommended next steps generated by Atlas. PDF + DOCX, ready to
            forward to your QSA, your underwriter, or your state auditor.
          </p>
          <div className="mt-6 flex flex-wrap gap-3">
            <Button asChild>
              <Link href="/sample-aar.pdf">Download the sample AAR</Link>
            </Button>
            <Button asChild variant="secondary">
              <Link href="/platform#aar">How AARs work</Link>
            </Button>
          </div>
        </div>
        <div className="relative">
          <article
            aria-label="Sample After-Action Report excerpt"
            className="rounded-lg border border-paper-200 bg-paper p-8 shadow-md ring-1 ring-paper-200"
          >
            <header className="border-b border-paper-200 pb-4">
              <p className="eyebrow text-navy/70">After-Action Report</p>
              <h3 className="mt-1 font-serif text-2xl font-semibold text-navy">
                County Election Systems — Ransomware Inject
              </h3>
              <p className="mt-1 text-xs text-ink-500">
                Conducted via Annual Tabletop · 60 minutes · 7 participants ·
                NIST 800-84 + FEMA HSEEP
              </p>
            </header>
            <dl className="mt-4 space-y-3 text-sm text-ink-700">
              <div>
                <dt className="font-semibold text-navy">Scenario summary</dt>
                <dd>
                  At 06:14, the BoE&apos;s ePollbook vendor reports a confirmed
                  ransomware encryption event 14 days before the November
                  general election.
                </dd>
              </div>
              <div>
                <dt className="font-semibold text-navy">Decisions captured</dt>
                <dd className="mt-1 list-decimal space-y-1 pl-4 [&>*]:list-decimal">
                  <p>Initiated COOP per ESF #2 within 22 minutes.</p>
                  <p>
                    Notified CISA and state CISO; held off public statement
                    pending verification.
                  </p>
                  <p>
                    Activated paper-pollbook contingency for 14 precincts.
                  </p>
                </dd>
              </div>
              <div>
                <dt className="font-semibold text-navy">Framework crosswalk</dt>
                <dd>
                  NIST CSF 2.0 RC.RP-1 · NIST 800-84 §3.4.3 · HSEEP Capability
                  Target #4 · CISA Election Security Toolkit §2
                </dd>
              </div>
            </dl>
            <footer className="mt-4 border-t border-paper-200 pt-3 text-[11px] text-ink-500">
              This is a sample AAR generated by Annual Tabletop. A real AAR
              includes deeper sections (participants, observations, evaluator
              notes, IPP). Try a full exercise at annualtabletop.com.
            </footer>
          </article>
        </div>
      </div>
    </section>
  );
}
